WebsiteBanHang/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    [Authorize(Roles = "QuanLy,QuanTriWeb")]
    public class QuanLySanPhamController : Controller
    {
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: QuanLySanPham
        public ActionResult Index()
        {

            return View(db.SanPhams.Where(n => n.DaXoa == false).OrderBy(n => n.MaSP));
        }

        [HttpGet]
        public ActionResult TaoMoi()
        {
            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sx
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");

            return View();
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult TaoMoi(SanPham sp, HttpPostedFileBase HinhAnh, HttpPostedFileBase HinhAnh1, HttpPostedFileBase HinhAnh2, HttpPostedFileBase HinhAnh3, HttpPostedFileBase HinhAnh4)
        {
            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sx
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");

            //ktra hình ảnh tồn tại trong csdl
            #region ThemHinhAnh
            if (HinhAnh != null)
            {
                if (HinhAnh.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(HinhAnh.FileName);  //Lấy tên hình
                    var path = Path.Combine(Server.MapPath("~/Content/HinhAnhSP"), fileName);   //lấy hình đưa vào folder HinhAnhSP

                    //lấy hình đưa vào folder
                    HinhAnh.SaveAs(path);
                    sp.HinhAnh = fileName;  //lưu vào sp
                }
            }
            if (HinhAnh1 != null)
            {
                if (HinhAnh1.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(HinhAnh1.FileName);  //Lấy tên hình
                    var path = Path.Combine(Server.MapPath("~/Content/HinhAnhSP"), fileName);   //lấy hình đưa vào folder HinhAnhSP

                    //lấy hình đưa vào folder
                    HinhAnh1.SaveAs(path);
                    sp.HinhAnh1 = fileName;  //lưu vào sp
                }
            }
            if (HinhAnh2 != null)
            {
                if (HinhAnh2.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(HinhAnh2.FileName);  //Lấy tên hình
                    var path = Path.Combine(Server.MapPath("~/Content/HinhAnhSP"), fileName);   //lấy hình đưa vào folder HinhAnhSP

                    //lấy hình đưa vào folder
                    HinhAnh2.SaveAs(path);
                    sp.HinhAnh2 = fileName;  //lưu vào sp
                }
            }
            if (HinhAnh3 != null)
            {
                if (HinhAnh3.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(HinhAnh3.FileName);  //Lấy tên hình
                    var path = Path.Combine(Server.MapPath("~/Content/HinhAnhSP"), fileName);   //lấy hình đưa vào folder HinhAnhSP

                    //lấy hình đưa vào folder
                    HinhAnh3.SaveAs(path);
                    sp.HinhAnh3 = fileName;  //lưu vào sp
                }
            }
            if (HinhAnh4 != null)
            {
                if (HinhAnh4.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(HinhAnh4.FileName);  //Lấy tên hình
                    var path = Path.Combine(Server.MapPath("~/Content/HinhAnhSP"), fileName);   //lấy hình đưa vào folder HinhAnhSP

                    //lấy hình đưa vào folder
                    HinhAnh4.SaveAs(path);
                    sp.HinhAnh4 = fileName;  //lưu vào sp
                }
            }

            #endregion


            db.SanPhams.Add(sp);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            //lấy sp cần chỉnh sửa
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }

            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sx
            ViewBag.MaNCC = TaoDanhSachMaNCC(sp.MaNCC.Value);
            ViewBag.MaLoaiSP = TaoDanhSachLoaiSP(sp.MaLoaiSP.Value);
            ViewBag.MaNSX = TaoDanhSachMaNSX(sp.MaNSX.Value);

            return View(sp);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua([Bind(Include = "MaSP,TenSP,DonGia,NgayCapNhat,Chitiet,MoTa,SoLuongTon,LuotXem,LuotBinhChon,LuotBinhLuan,SoLuotMua,Moi,MaNCC,MaNSX,MaLoaiSP,DaXoa")] SanPham sp)
        {

            if (ModelState.IsValid)
            {
                SanPham sanPham = db.SanPhams.Find(sp.MaSP);
                TryUpdateModel(sanPham, new string[] { "MaSP", "TenSP", "DonGia", "NgayCapNhat", "Chitiet", "MoTa",
                "SoLuongTon", "LuotXem", "LuotBinhChon", "LuotBinhLuan", "SoLuotMua","Moi","MaNCC","MaNSX","MaLoaiSP","DaXoa"});
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", sp.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams, "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats, "MaNSX", "TenNSX", sp.MaNSX);

            return View(sp);
        }

        [HttpGet]
        public ActionResult UploadHinh(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.Find(id);
            if (sp == null)
            {
                return HttpNotFound();
            }

            return View(sp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadHinh(int id, HttpPostedFileBase HinhAnh, HttpPostedFileBase HinhAnh1, HttpPostedFileBase HinhAnh2, HttpPostedFileBase HinhAnh3, HttpPostedFileBase HinhAnh4)
        {
            SanPham sp = db.SanPhams.Find(id);

            if (HinhAnh != null)
            {
                string path = Server.MapPath("~/Content/HinhAnhSP/");
                string Ten = null;
                HinhAnh.SaveAs(path + HinhAnh.FileName);
                Ten = HinhAnh.FileName;

                if (!string.IsNullOrEmpty(sp.HinhAnh))
                {
                    string pathAndFname = Server.MapPath($"~/Content/HinhAnhSP/{sp.HinhAnh}");
                    if (System.IO.File.Exists(pathAndFname))
                        System.IO.File.Delete(pathAndFname);
                }
                sp.HinhAnh = Ten;
            }
            if (HinhAnh1 != null)
            {
                string path = Server.MapPath("~/Content/HinhAnhSP/");
                string Ten = null;
                HinhAnh1.SaveAs(path + HinhAnh1.FileName);
                Ten = HinhAnh1.FileName;

                if (!string.IsNullOrEmpty(sp.HinhAnh1))
                {
                    string pathAndFname = Server.MapPath($"~/Content/HinhAnhSP/{sp.HinhAnh1}");
                    if (System.IO.File.Exists(pathAndFname))
                        System.IO.File.Delete(pathAndFname);
                }
                sp.HinhAnh1 = Ten;
            }
            if (HinhAnh2 != null)
            {
                string path = Server.MapPath("~/Content/HinhAnhSP/");
                string Ten = null;
                HinhAnh2.SaveAs(path + HinhAnh2.FileName);
                Ten = HinhAnh2.FileName;

                if (!string.IsNullOrEmpty(sp.HinhAnh2))
                {
                    string pathAndFname = Server.MapPath($"~/Content/HinhAnhSP/{sp.HinhAnh2}");
                    if (System.IO.File.Exists(pathAndFname))
                        System.IO.File.Delete(pathAndFname);
                }
                sp.HinhAnh2 = Ten;
            }
            if (HinhAnh3 != null)
            {
                string path = Server.MapPath("~/Content/HinhAnhSP/");
                string Ten = null;
                HinhAnh3.SaveAs(path + HinhAnh3.FileName);
                Ten = HinhAnh3.FileName;

                if (!string.IsNullOrEmpty(sp.HinhAnh3))
                {
                    string pathAndFname = Server.MapPath($"~/Content/HinhAnhSP/{sp.HinhAnh3}");
                    if (System.IO.File.Exists(pathAndFname))
                        System.IO.File.Delete(pathAndFname);
                }
                sp.HinhAnh3 = Ten;
            }
            if (HinhAnh4 != null)
            {
                string path = Server.MapPath("~/Content/HinhAnhSP/");
                string Ten = null;
                HinhAnh4.SaveAs(path + HinhAnh4.FileName);
                Ten = HinhAnh4.FileName;

                if (!string.IsNullOrEmpty(sp.HinhAnh4))
                {
                    string pathAndFname = Server.MapPath($"~/Content/HinhAnhSP/{sp.HinhAnh4}");
                    if (System.IO.File.Exists(pathAndFname))
                        System.IO.File.Delete(pathAndFname);
                }
                sp.HinhAnh4 = Ten;
            }

WebsiteBanHang/Views/QuanLySanPham/Index.cshtml
@using WebsiteBanHang.Models;
@model IEnumerable<SanPham>
@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

}

<h2>@ViewBag.Title</h2>
<div class="card">
    <div class="card-body">
        <p>
            @Html.ActionLink("Thêm mới", "TaoMoi", null, htmlAttributes: new { @class = "btn btn-sm btn-warning font-weight-bold " })
        </p>
        <div id="divPartialView">
            @Html.Partial("_IndexPartial")
        </div>
    </div>
</div>

WebsiteBanHang/Views/QuanLySanPham/KhongTheXoa.cshtml
@{
    ViewBag.Title = "Error 404";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Không thể xóa vì liên quan đến khóa chính trong csdl</h2>

WebsiteBanHang/Views/QuanLySanPham/UploadHinh.cshtml
@model WebsiteBanHang.Models.SanPham
@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Sản Phẩm", "Index") > Upload hình</h4>
<div class="card shadow">
    <div class="card-body">
        <h3 class="text-info mb-3">Tên sản phẩm: @Model.TenSP</h3>
        <div class="text-danger"> @ViewBag.ThongBao</div>

        @using (Html.BeginForm("UploadHinh", "QuanLySanPham", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <h4>Hình ảnh</h4>
            <div class="custom-file mb-3">
                <input type="file" class="custom-file-input" id="inputfile" name="HinhAnh" multiple>
                <label class="custom-file-label" for="inputfile">Chọn hình ảnh</label>
            </div>

            <h4>Hình ảnh 1</h4>
            <div class="custom-file mb-3">
                <input type="file" class="custom-file-input" id="inputfile" name="HinhAnh1" multiple>
                <label class="custom-file-label" for="inputfile">Chọn hình ảnh</label>
            </div>

            <h4>Hình ảnh 2</h4>
            <div class="custom-file mb-3">
                <input type="file" class="custom-file-input" id="inputfile" name="HinhAnh2" multiple>
                <label class="custom-file-label" for="inputfile">Chọn hình ảnh</label>
            </div>

            <h4>Hình ảnh 3</h4>
            <div class="custom-file mb-3">
                <input type="file" class="custom-file-input" id="inputfile" name="HinhAnh3" multiple>
                <label class="custom-file-label" for="inputfile">Chọn hình ảnh</label>
            </div>

            <h4>Hình ảnh 4</h4>
            <div class="custom-file mb-3">
                <input type="file" class="custom-file-input" id="inputfile" name="HinhAnh4" multiple>
                <label class="custom-file-label" for="inputfile">Chọn hình ảnh</label>
            </div>

            <div class="form-group mt-4">
                <button type="submit" class="btn btn-primary">Upload</button>
                @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary " })
            </div>
        }
    </div>
</div>

WebsiteBanHang/Views/QuanLySanPham/Xoa.cshtml
@model WebsiteBanHang.Models.SanPham

@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Sản Phẩm", "Index") > Xóa</h4>
<div class="card shadow">
    <div class="card-body">
        <h4 class="card-title">Thông tin sản phẩm</h4>
        <hr />
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaSP)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaSP)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.TenSP)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.TenSP)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.DonGia)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.DonGia)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.NgayCapNhat)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.NgayCapNhat)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.Chitiet)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.Chitiet)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.HinhAnh)</label>
            <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh)" class="img-thumbnail" alt="Cinque Terre" width="200" height="200">

        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.LuotXem)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.LuotXem)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.LuotBinhChon)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.LuotBinhChon)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.LuotBinhLuan)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.LuotBinhLuan)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaNCC)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaNCC)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaNSX)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaNSX)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaLoaiSP)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaLoaiSP)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.DaXoa)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.DaXoa)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.HinhAnh1)</label>
            <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh1)" class="img-thumbnail" alt="Cinque Terre" width="200" height="200">

        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.HinhAnh2)</label>
            <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh2)" class="img-thumbnail" alt="Cinque Terre" width="200" height="200">
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.HinhAnh3)</label>
            <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh3)" class="img-thumbnail" alt="Cinque Terre" width="200" height="200">
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.HinhAnh4)</label>
            <img src="@Url.Content("~/Content/HinhAnhSP/" + Model.HinhAnh4)" class="img-thumbnail" alt="Cinque Terre" width="200" height="200">
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MoTa)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MoTa, "", new { @class = "overflow-auto" })</div>
        </div>

        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-4">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Xóa" class="btn btn-sm btn-primary font-weight-bold w-25" />
                    @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                }
            </div>
        </div>

     
    </div>
</div>

WebsiteBanHang/Views/QuanLySanPham/_IndexPartial.cshtml
@{
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10); //khởi tạo control webgird
}

@* Thể hiện dữ liệu qua webgird *@

@if (grid != null)
{
    <div id="list" class="table-responsive">
        @grid.GetHtml(
        tableStyle: "table table-bordered table-hover",
        headerStyle: "",
        footerStyle: "text-center",
        numericLinksCount: 10,
        mode: WebGridPagerModes.All, firstText: "Trang đầu", lastText: "Trang cuối",
        columns: grid.Columns(
            grid.Column("MaSP", "Mã SP"),
            grid.Column("TenSP", "Tên SP"),
            grid.Column("HinhAnh", "Hình ảnh", format: p => Html.Raw("<img width=\"150\" height=\"150\" src=\"../Content/HinhAnhSP/" + p.HinhAnh + "\">")),
            grid.Column("SoLuongTon", "Tồn kho"),
            grid.Column("DonGia", "Đơn giá", format: p=>p.DonGia.ToString("#,##")),
            grid.Column("LoaiSanPham.TenLoai", "Loại"),
            grid.Column("NhaSanXuat.TenNSX", "NSX"),
            grid.Column(format: p => Html.ActionLink("Chỉnh sửa", "ChinhSua", new { id = p.MaSP })),
            grid.Column(format: p => Html.ActionLink("Xóa", "Xoa", new { id = p.MaSP })),
            grid.Column(format: p => Html.ActionLink("Upload Hình", "UploadHinh", new { id = p.MaSP }))
            )
        )
    </div>
}