WebsiteBanHang/Controllers/QuanLyThanhVienController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    [Authorize(Roles = "QuanTriWeb")]
    public class QuanLyThanhVienController : Controller
    {
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: QuanLyThanhVien
        public ActionResult Index()
        {
            return View(db.ThanhViens.OrderBy(n => n.MaThanhVien));
        }
        [HttpGet]
        public ActionResult TaoMoi()
        {
            ViewBag.CauHoi = new SelectList(LoadCauHoi());
            ViewBag.MaLoaiTV = new SelectList(db.LoaiThanhViens.OrderBy(n => n.MaLoaiTV), "MaLoaiTV", "TenLoai");

            return View();
        }
        [HttpPost]
        public ActionResult TaoMoi(ThanhVien tv)
        {
            ViewBag.CauHoi = new SelectList(LoadCauHoi());
            ViewBag.MaLoaiTV = new SelectList(db.LoaiThanhViens.OrderBy(n => n.MaLoaiTV), "MaLoaiTV", "TenLoai");

            db.ThanhViens.Add(tv);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            //lấy sp cần chỉnh sửa
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.MaThanhVien == id);
            if (tv == null)
            {
                return HttpNotFound();
            }
            ViewBag.CauHoi = new SelectList(LoadCauHoi(), selectedValue: tv.CauHoi);
            ViewBag.MaLoaiTV = TaoDanhSachLoaiTV(tv.MaLoaiTV.Value);
            return View(tv);
        }

        [HttpPost]
        public ActionResult ChinhSua(ThanhVien tv)
        {
            if (ModelState.IsValid)
            {
                ThanhVien thanhVien = db.ThanhViens.Find(tv.MaThanhVien);
                TryUpdateModel(thanhVien, new string[] { "MaSP", "TaiKhoan", "MatKhau", "HoTen", "DiaChi", "Email",
                                                        "SoDienThoai", "CauHoi", "CauTraLoi", "MaLoaiTV" });

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CauHoi = new SelectList(tv.CauHoi);
            ViewBag.MaLoaiTV = new SelectList(db.LoaiThanhViens, "MaLoaiTV", "TenLoai", tv.MaLoaiTV);
            return View(tv);
        }

        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            //lấy sp cần chỉnh sửa
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.MaThanhVien == id);
            if (tv == null)
            {
                return HttpNotFound();
            }
            ViewBag.CauHoi = new SelectList(LoadCauHoi(), selectedValue: tv.CauHoi);
            ViewBag.MaLoaiTV = TaoDanhSachLoaiTV(tv.MaLoaiTV.Value);
            return View(tv);
        }

        [HttpPost]
        public ActionResult Xoa(int id)
        {
            //lấy sp cần chỉnh sửa
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            ThanhVien tv = db.ThanhViens.SingleOrDefault(n => n.MaThanhVien == id);
            if (tv == null)
            {
                return HttpNotFound();
            }
            db.ThanhViens.Remove(tv);
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        private SelectList TaoDanhSachLoaiTV(int IDChon = 0)
        {
            var items = db.LoaiThanhViens.Select(p => new { p.MaLoaiTV, ThongTin = p.TenLoai }).ToList();
            var result = new SelectList(items, "MaLoaiTV", "ThongTin", selectedValue: IDChon);
            return result;
        }

        //Load câu hỏi để đưa vào dropdownlist
        public List<string> LoadCauHoi()
        {
            List<string> lstCauHoi = new List<string>();    //tạo list câu hỏi chứa câu hỏi
            lstCauHoi.Add("Họ tên người cha bạn là gì?");
            lstCauHoi.Add("Ca sĩ mà bạn yêu thích là ai?");
            lstCauHoi.Add("Vật nuôi mà bạn yêu thích là gì?");
            lstCauHoi.Add("Sở thích của bạn là gì");
            lstCauHoi.Add("Hiện tại bạn đang làm công việc gì?");
            lstCauHoi.Add("Trường cấp ba bạn học là gì?");
            lstCauHoi.Add("Năm sinh của mẹ bạn là gì?");
            lstCauHoi.Add("Bộ phim mà bạn yêu thích là gì?");
            lstCauHoi.Add("Bài nhạc mà bạn yêu thích là gì?");

            return lstCauHoi;
        }

        //Giải phóng dung lượng biến db, để ở cuối controller
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebsiteBanHang/Views/QuanLyThanhVien/ChinhSua.cshtml
@model WebsiteBanHang.Models.ThanhVien
@{
    ViewBag.Title = "Quản lý thành viên";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Quản lý thành viên", "Index") > Chỉnh sửa</h4>
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("ChinhSua", "QuanLyThanhVien", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.Hidden("MaThanhVien", Model.MaThanhVien)

            <div class="form-group row">
                @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.CauHoi, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.DropDownList("CauHoi", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.CauTraLoi, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.CauTraLoi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CauTraLoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.MaLoaiTV, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.DropDownList("MaLoaiTV", null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group row ">
                <div class="col-sm-4 mt-3">
                    <input type="submit" value="Chỉnh sửa" class="btn btn-sm btn-primary font-weight-bold w-25" />
                    @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                </div>
            </div>
        </div>
        }
    </div>
</div>

WebsiteBanHang/Views/QuanLyThanhVien/Index.cshtml
@using WebsiteBanHang.Models
@model IEnumerable<ThanhVien>
@{
    ViewBag.Title = "Quản lý thành viên";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<h2>@ViewBag.Title</h2>
<div class="card">
    <div class="card-body">
        <p>
            @Html.ActionLink("Thêm mới", "TaoMoi", null, htmlAttributes: new { @class = "btn btn-sm btn-warning font-weight-bold " })
        </p>
        @if (grid != null)
        {
            <div id="list" class="table-responsive">
                @grid.GetHtml(
                tableStyle: "table table-bordered table-hover",
                headerStyle: "",
                footerStyle: "text-center",
                numericLinksCount: 10,
                mode: WebGridPagerModes.All, firstText: "Trang đầu", lastText: "Trang cuối",
                columns: grid.Columns(
                    grid.Column("MaThanhVien", "Mã TV"),
                    grid.Column("TaiKhoan", "Tài khoản"),
                    grid.Column("HoTen", "Họ tên"),
                    grid.Column("DiaChi", "Địa chỉ"),
                    grid.Column("Email", "Email"),
                    grid.Column("SoDienThoai", "SĐT"),
                    grid.Column("LoaiThanhVien.TenLoai", "Loại TV"),
                    grid.Column(format: p => Html.ActionLink("Chỉnh sửa", "ChinhSua", new { id = p.MaThanhVien })),
                    grid.Column(format: p => Html.ActionLink("Xóa", "Xoa", new { id = p.MaThanhVien }))
                    )
                )
            </div>
        }
    </div>
</div>

WebsiteBanHang/Views/QuanLyThanhVien/TaoMoi.cshtml
@model WebsiteBanHang.Models.ThanhVien
@{
    ViewBag.Title = "Quản lý thành viên";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Quản lý thành viên", "Index") > Tạo mới</h4>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Tạo mới thành viên</h4>
        @using (Html.BeginForm("TaoMoi", "QuanLyThanhVien", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <br />
                <div class="form-group row">
                    @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.CauHoi, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.DropDownList("CauHoi", null, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.CauTraLoi, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.CauTraLoi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CauTraLoi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.MaLoaiTV, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.DropDownList("MaLoaiTV", null, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group row ">
                    <div class="col-sm-4 mt-3">
                        <input type="submit" value="Thêm mới" class="btn btn-sm btn-primary font-weight-bold w-25" />
                        @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

WebsiteBanHang/Views/QuanLyThanhVien/Xoa.cshtml
@model WebsiteBanHang.Models.ThanhVien
@{
    ViewBag.Title = "Quản lý thành viên";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Quản lý thành viên", "Index") > Xóa</h4>
<div class="card shadow">
    <div class="card-body">
        <h4 class="card-title">Thông tin thành viên</h4>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaThanhVien)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaThanhVien)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.TaiKhoan)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.TaiKhoan)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MatKhau)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MatKhau)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.HoTen)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.HoTen)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.DiaChi)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.DiaChi)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.Email)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.Email)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.SoDienThoai)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.SoDienThoai)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.CauHoi)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.CauHoi)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.CauTraLoi)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.HoTen)</div>
        </div>
        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaLoaiTV)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaLoaiTV)</div>
        </div>

        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-4">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Xóa" class="btn btn-sm btn-primary font-weight-bold w-25" />
                    @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                }
            </div>
        </div>
    </div>
</div>