WebsiteBanHang/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Models;
using PagedList;

namespace WebsiteBanHang.Controllers
{
    public class TimKiemController : Controller
    {

        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: TimKiem
        [HttpGet]
        public ActionResult KQTimKiem(string sTuKhoa, int? page)
        {
            //Phân trang
            if (Request.HttpMethod != "GET")
                page = 1;
            //tạo biến số sản phẩm trên trang
            int PageSize = 6;
            //tạo biến số trang hiện tại
            int PageNumber = (page ?? 1);
            //tìm kiếm theo tên sản phẩm
            var lstSP = db.SanPhams.Where(n => n.TenSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;

            return View(lstSP.OrderBy(n=>n.TenSP).ToPagedList(PageNumber,PageSize));
        }
        [HttpPost]
        public ActionResult LayTuKhoaTimKiem(string sTuKhoa)
        {
            //gọi về hàm get tìm kiếm

            return RedirectToAction("KQTimKiem", new {@sTuKhoa = sTuKhoa });
        }
    }
}

WebsiteBanHang/Views/Layout/AdminLayout.cshtml
@using WebsiteBanHang.Models
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/AdminLayout/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/AdminLayout/css/sb-admin-2.min.css" rel="stylesheet">
    <script src="~/Content/AdminLayout/vendor/jquery/jquery.min.js"></script>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- #region Phần menu trái -->
        @if (Session["TaiKhoan"] != null && Session["TaiKhoan"].ToString() != "")
        {
            ThanhVien tv = (ThanhVien)Session["TaiKhoan"];     //ép kiểu từ biến session thành biến tv để lấy ra thông tin
            if (tv.MaLoaiTV == 1)
            {
                <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                    <!-- Sidebar - Brand -->
                    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                        <div class="sidebar-brand-icon rotate-n-15">
                            <i class="fas fa-laugh-wink"></i>
                        </div>
                        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
                    </a>

                    <!-- Divider -->
                    <hr class="sidebar-divider my-0">

                    <!-- Nav Item - Dashboard -->
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index","ThongKe")">
                            <i class="fas fa-fw fa-tachometer-alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>

                    <!-- Divider -->
                    <hr class="sidebar-divider">

                    <!-- Heading -->
                    <div class="sidebar-heading">
                        Admin
                    </div>

                    <!-- Nav Item - Pages Collapse Menu -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","QuanLyThanhVien")">
                            <i class="fas fa-fw fa-chart-area"></i>
                            <span>Thành viên</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","QuanLyQuyen")">
                            <i class="fas fa-fw fa-chart-area"></i>
                            <span>Quản lý quyền</span>
                        </a>
                    </li>

                    <!-- Nav Item - Utilities Collapse Menu -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","PhanQuyen")">
                            <i class="fas fa-fw fa-chart-area"></i>
                            <span>Phân quyền</span>
                        </a>
                    </li>

                    <!-- Divider -->
                    <hr class="sidebar-divider">

                    <!-- Heading -->
                    <div class="sidebar-heading">
                        Quản lý
                    </div>

                    <!-- Nav Item - Pages Collapse Menu -->
                    <!-- Nav Item - Charts -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ChuaThanhToan","QuanLyDonHang")">
                            <i class="fas fa-fw fa-chart-area"></i>
                            <span>Đơn hàng</span>
                        </a>
                    </li>

                    <!-- Nav Item - Tables -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("NhapHang","QuanLyPhieuNhap")">
                            <i class="fas fa-fw fa-table"></i>
                            <span>Nhập hàng</span>
                        </a>
                    </li>

                    <!-- Nav Item - Tables -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("DSSPHetHang","QuanLyPhieuNhap")">
                            <i class="fas fa-fw fa-table"></i>
                            <span>Sản phẩm gần hết</span>
                        </a>
                    </li>

                    <!-- Divider -->
                    <hr class="sidebar-divider">

                    <!-- Heading -->
                    <div class="sidebar-heading">
                        Danh mục
                    </div>

                    <!-- Nav Item - Tables -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","QuanLyLoai")">
                            <i class="fas fa-fw fa-table"></i>
                            <span>Loại</span>
                        </a>
                    </li>

                    <!-- Nav Item - Tables -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","QuanLySanPham")">
                            <i class="fas fa-fw fa-table"></i>
                            <span>Sản phẩm</span>
                        </a>
                    </li>

                    <!-- Nav Item - Tables -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","QuanLyNhaSX")">
                            <i class="fas fa-fw fa-table"></i>
                            <span>Nhà sản xuất</span>
                        </a>
                    </li>

                    <!-- Divider -->
                    <hr class="sidebar-divider d-none d-md-block">

                    <!-- Sidebar Toggler (Sidebar) -->
                    <div class="text-center d-none d-md-inline">
                        <button class="rounded-circle border-0" id="sidebarToggle"></button>
                    </div>

                </ul>
            }
        }
        else
        {
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                    <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-laugh-wink"></i>
                    </div>
                    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
                </a>

                <!-- Divider -->
                <hr class="sidebar-divider my-0">

                <!-- Nav Item - Dashboard -->
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index","ThongKe")">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Không Có Quyền</span>
                    </a>
                </li>

            </ul>
        }
        <!-- #endregion -->
        <!-- Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                @Html.Partial("~/Views/Layout//_AdminHeaderPartial.cshtml")

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>


            </div>

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; giahuyle1@gmail.com</span>
                    </div>
                </div>
            </footer>

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>
    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>
    <!-- Page level custom scripts -->
    <script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>

    @RenderSection("Scripts", false)
    @section Scripts{
        <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    }
</body>
</html>
<script>
    $("#sidebarToggle").on('click', function (e) {
        $("body").toggleClass("sidebar-toggled");
        $(".sidebar").toggleClass("toggled");
        if ($(".sidebar").hasClass("toggled")) {
            $('.sidebar .collapse').collapse('hide');
        };
    });
</script>

WebsiteBanHang/Views/Layout/BaoLoi.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body style="background-color: #3F3043">
    <div class="container-fluid">
        <div class="row pt-5">
            <div class="col-sm-6 d-flex flex-wrap align-items-center justify-content-end">
                <img src="~/images/Error404.jpg" style="width:70%" />
            </div>
            <div class="col-sm-6 d-flex flex-wrap align-content-center ">
                <div class="text-white font-weight-bold">
                    <h4>@Html.Raw(Model)</h4>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

WebsiteBanHang/Views/Layout/HeaderTopPartial.cshtml
@using WebsiteBanHang.Models

<div class="header-top">
    <div class="container">
        @* Tạo form submit về action tìm kiếm *@
        @using (Html.BeginForm("LayTuKhoaTimKiem", "TimKiem"))
        {
            <div class="search">
                <form>
                    <input class="TimKiem" type="text" name="sTuKhoa" value="Từ Khóa " onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Từ Khóa';}">
                    <input type="submit" value="Tìm kiếm">
                </form>
            </div>
        }
        <div class="header-left">
            <ul>
                @if(Session["TaiKhoan"] != null && Session["TaiKhoan"].ToString() != "")
                {
                    ThanhVien tv = (ThanhVien)Session["TaiKhoan"];     //ép kiểu từ biến session thành biến tv để lấy ra thông tin
                    if (tv.MaLoaiTV == 1)
                    {
                        <li style="display:inline;"><a class="lock" href="@Url.Action("Index", "ThongKe")">Trang quản lý</a></li>
                    }

                    <li style="display:inline; color:white; font-size:17px; margin-right:15px;">Chào @tv.HoTen </li>
                    <li><a class="lock" href="@Url.Action("DangXuat", "Home")">Đăng xuất</a>  </li>
                    @*@Html.ActionLink("Đăng xuất", "DangXuat", "Home", new { @class = "lock" })*@
                }
                else
                {
                    <li style="display:inline;"><a id="btnDangNhap" class="lock" href="#">Đăng nhập</a></li>
                    <li style="display:inline;"><a class="lock" href="@Url.Action("DangKy", "Home")">Đăng ký</a></li>
                }


            </ul>
            <!--chèn partial view giỏ hàng vào layout (tách icon giỏ hàng sang 1 partial view mới)-->
            @Html.Action("GioHangPartial", "GioHang")
            <div class="clearfix"> </div>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>


<!--login form-->

<link href="~/Content/css/Style_form_dangNhap.css" rel='stylesheet' type='text/css' />

<div>
    <br />
    <div id="popup_login">
        <div class="login-form" id="login-form">
            <div style="clear:both;text-align:right;margin-bottom:0">
                <span id="close-form" class="btn btn-danger">X</span>
            </div>
            <h2>Đăng nhập</h2>
            <div class="form-info">
                <!--Dùng ajax để hiển thị thông báo khi đăng nhập-->
                @using (Ajax.BeginForm("DangNhap", "Home", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "ThongBao" }))
                {

                    <input type="text" class="email" name="txtTenDangNhap" placeholder="Tên đăng nhập" required="" />
                    <input type="password" class="password" name="txtMatKhau" placeholder="Mật khẩu" required="" />
                    <p><a href="#">Quên mật khẩu?</a></p>
                    <h3 id="ThongBao" style="font-weight:bold; color:crimson; text-align:left"></h3>
                    <ul class="login-buttons">
                        <li><input type="submit" class="btn-summit" value="Đăng nhập" style="height: 51px; width: 199px;" /></li>
                        <li><a href="#" class="btn-summit hvr-sweep-to-left" style="min-width: 150px; height: 47px; font-size: 16px; text-decoration:none">đăng ký</a></li>
                    </ul>
                }
            </div>
        </div>
    </div>
</div>

<style>
    .search .TimKiem {
        color: #c7c7c7 !important;
        font-weight: inherit !important;
    }

    #close-form {
        color: white;
    }

    #popup_login {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0,0,0,0.5);
        z-index: 1000;
        display: none;
        text-align: center;
    }

    .btn-summit:hover {
        background: rgba(54, 185, 204);
        color: #fff;
        transition: 0.6s all;
        -webkit-transition: 0.6s all;
        -moz-transition: 0.6s all;
        -o-transition: 0.6s all;
    }

    .btn-summit {
        background: rgba(63, 101, 212);
        color: #fff;
        padding: 15px 60px;
        font-size: 1.1em;
        font-weight: 600;
        margin-right: 27px;
        border-radius: 3px;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        outline: none;
        border: none;
        cursor: pointer;
    }
</style>

<script type="text/javascript">
    $("#btnDangNhap").click(function () {
        $("#popup_login").show();
    });
    $("#close-form").click(function () {
        $("#popup_login").hide();
    });
</script>

WebsiteBanHang/Views/Layout/HomeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <link href="~/Content/fontawesome/css/all.css" rel="stylesheet" type="text/css" media="all">
    <link href="~/Content/fontawesome/css/all.min.css" rel="stylesheet" type="text/css" media="all">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Content/js/jquery.min.js"></script>
    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="~/Content/css/Home_style.css" rel="stylesheet" type="text/css" media="all">
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="New Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design">
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--fonts-->
    <link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900" rel="stylesheet" type="text/css"><!--//fonts-->
    <!-- start menu -->
    <link href="~/Content/css/memenu.css" rel="stylesheet" type="text/css" media="all">
    <script type="text/javascript" src="~/Content/js/memenu.js"></script>
    <script>$(document).ready(function () { $(".memenu").memenu(); });</script>
    <script src="~/Content/js/simpleCart.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body>
    <!--header-->
    <div class="header">
        @Html.Partial("~/Views/Layout//HeaderTopPartial.cshtml")
        <div class="container">
            <div class="head-top">
                <div class="logo">
                    <a href="#"><img src="images/logo.png" alt=""></a>
                </div>
                @Html.Action("MenuPartial", "Home")

                <div class="clearfix"> </div>
            </div>
        </div>

    </div>


    <div class="banner">
        <div class="container">
            <script src="~/Content/js/responsiveslides.min.js"></script>
            <script>
                $(function () {
                    $("#slider").responsiveSlides({
                        auto: true,
                        nav: true,
                        speed: 500,
                        namespace: "callbacks",
                        pager: true,
                    });
                });
            </script>
            <div id="top" class="callbacks_container">
                <ul class="rslides callbacks callbacks1" id="slider">
                    <li id="callbacks1_s0" class="" style="display: block; float: none; position: absolute; opacity: 0; z-index: 1; transition: opacity 500ms ease-in-out 0s;">

                        <div class="banner-text">
                            <h3>Giày cao nam GOG nhập khẩu </h3>
                            <p>Lựa chọn một đôi giày công sở đơn giản, lịch sự kết hợp với nhiều trang phục là tiêu chí lựa chọn của cánh đàn ông.</p>
                            <a href="@Url.Action("SanPham","SanPham",new {@MaLoaiSP = 1, @MaNSX = 4})">Xem thêm</a>
                        </div>

                    </li>
                    <li id="callbacks1_s1" class="callbacks1_on" style="float: left; position: relative; opacity: 1; z-index: 2; display: list-item; transition: opacity 500ms ease-in-out 0s;">

                        <div class="banner-text">
                            <h3>Giày buộc dây da bò HongKong nhập khẩu </h3>
                            <p>Thương hiệu giày da HongKong- TAIWAN đã nổi tiếng rất nhiều năm về sự uy tín, chất lượng da giày luôn tốt nhất phân khúc giá</p>
                            <a href="@Url.Action("SanPham","SanPham",new {@MaLoaiSP = 1, @MaNSX = 4})">Xem thêm</a>
                        </div>
                    </li>
                    <li id="callbacks1_s2" class="" style="float: none; position: absolute; opacity: 0; z-index: 1; display: list-item; transition: opacity 500ms ease-in-out 0s;">
                        <div class="banner-text">
                            <h3>Giày buộc dây nam cao cấp; BD2277D</h3>
                            <p>Giày buộc dây nam cao cấp; BD2277D nhập khẩu được làm trên chất liệu da bò mềm nguyên tấm 100%, phong cách thiết kế giày nam tối giản cực kỳ hợp với xu hướng giày công sở hiện nay</p>
                            <a href="@Url.Action("SanPham","SanPham",new {@MaLoaiSP = 1, @MaNSX = 4})">Xem thêm</a>
                        </div>
                    </li>
                </ul>
                <a href="#" class="callbacks_nav callbacks1_nav prev">Previous</a><a href="#" class="callbacks_nav callbacks1_nav next">Next</a><ul class="callbacks_tabs callbacks1_tabs"><li class="callbacks1_s1"><a href="#" class="callbacks1_s1">1</a></li><li class="callbacks1_s2 callbacks_here"><a href="#" class="callbacks1_s2">2</a></li><li class="callbacks1_s3"><a href="#" class="callbacks1_s3">3</a></li></ul>
            </div>

        </div>
    </div>

    <!--content-->
    <div class="content">
        @RenderBody()

    </div>
    <!-- #region Phần footer -->
    <div class="footer">
        <div class="container">
            <div class="footer-top-at">

                <div class="col-md-4 amet-sed">
                    <h4>Thông Tin Chung</h4>
                    <ul class="nav-bottom">
                        <li><a href="#">Giới Thiệu</a></li>
                        <li><a href="#">Tin Tuyển Dụng</a></li>
                        <li><a href="contact.html">Tin Tức</a></li>
                        <li><a href="#">Tin Khuyến Mãi</a></li>
                        <li><a href="#">Chính Sách Bảo Hành</a></li>
                    </ul>
                </div>
                <div class="col-md-4 amet-sed ">
                    <h4>HỖ TRỢ KHÁCH HÀNG</h4>
                    <p>Mua Giá Sỉ Và Lẻ</p>
                    <p>Vận chuyể toàn quốc</p>
                    <p>Chính Sách Đổi Hàng</p>
                    <ul class="social">
                        <li><a href="#"><i> </i></a></li>
                        <li><a href="#"><i class="twitter"> </i></a></li>
                        <li><a href="#"><i class="rss"> </i></a></li>
                        <li><a href="#"><i class="gmail"> </i></a></li>

                    </ul>
                </div>
                <div class="col-md-4 amet-sed">
                    <h4>Nhận Thông Tin Khuyến Mãi</h4>
                    <p>
                        Nhập Địa Chỉ Email Để Nhận Thông Báo Mới Nhất
                    </p>
                    <form>
                        <input type="text" placeholder="Email@gmail.com" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
                        <input type="submit" value="Gửi">
                    </form>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <!-- #endregion -->
</body>
</html>

WebsiteBanHang/Views/Layout/RegisterLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>New Store A Ecommerce Category Flat Bootstarp Resposive Website Template | Home :: w3layouts</title>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <link href="~/Content/fontawesome/css/all.css" rel="stylesheet" type="text/css" media="all">
    <link href="~/Content/fontawesome/css/all.min.css" rel="stylesheet" type="text/css" media="all">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Content/js/jquery.min.js"></script>
    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="~/Content/css/Home_style.css" rel="stylesheet" type="text/css" media="all">
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="New Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design">
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--fonts-->
    <link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900" rel="stylesheet" type="text/css"><!--//fonts-->
    <!-- start menu -->
    <link href="~/Content/css/memenu.css" rel="stylesheet" type="text/css" media="all">
    <script type="text/javascript" src="~/Content/js/memenu.js"></script>
    <script>$(document).ready(function () { $(".memenu").memenu(); });</script>
    <script src="~/Content/js/simpleCart.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
</head>
<body>
    <!--header-->
    <div class="header">
        @Html.Partial("~/Views/Layout//HeaderTopPartial.cshtml")
        <div class="container">
            <div class="head-top">
                <div class="logo">
                    <a href="index.html"><img src="images/logo.png" alt=""></a>
                </div>
                @Html.Action("MenuPartial", "Home")

                <div class="clearfix"> </div>
            </div>
        </div>

    </div>

    <!--content-->
    <div class="content">
        @RenderBody()
    </div>
    <!-- #region Phần footer -->
    <div class="footer">
        <div class="container">
            <div class="footer-top-at">

                <div class="col-md-4 amet-sed">
                    <h4>Thông Tin Chung</h4>
                    <ul class="nav-bottom">
                        <li><a href="#">Giới Thiệu</a></li>
                        <li><a href="#">Tin Tuyển Dụng</a></li>
                        <li><a href="contact.html">Tin Tức</a></li>
                        <li><a href="#">Tin Khuyến Mãi</a></li>
                        <li><a href="#">Chính Sách Bảo Hành</a></li>
                    </ul>
                </div>
                <div class="col-md-4 amet-sed ">
                    <h4>HỖ TRỢ KHÁCH HÀNG</h4>
                    <p>Mua Giá Sỉ Và Lẻ</p>
                    <p>Vận chuyể toàn quốc</p>
                    <p>Chính Sách Đổi Hàng</p>
                    <ul class="social">
                        <li><a href="#"><i> </i></a></li>
                        <li><a href="#"><i class="twitter"> </i></a></li>
                        <li><a href="#"><i class="rss"> </i></a></li>
                        <li><a href="#"><i class="gmail"> </i></a></li>

                    </ul>
                </div>
                <div class="col-md-4 amet-sed">
                    <h4>Nhận Thông Tin Khuyến Mãi</h4>
                    <p>
                        Nhập Địa Chỉ Email Để Nhận Thông Báo Mới Nhất
                    </p>
                    <form>
                        <input type="text" placeholder="Email@gmail.com" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
                        <input type="submit" value="Gửi">
                    </form>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <!-- #endregion -->
</body>
</html>