WebsiteBanHang/Controllers/QuanLyQuyenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    [Authorize(Roles = "QuanTriWeb")]
    public class QuanLyQuyenController : Controller
    {
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        // GET: QuanLyQuyen
        public ActionResult Index()
        {
            return View(db.Quyens.OrderBy(n => n.TenQuyen));
        }

        [HttpGet]
        public ActionResult TaoMoi()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TaoMoi(Quyen quyen)
        {
            db.Quyens.Add(quyen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ChinhSua(string id)
        {
            if (id == "")
            {
                Response.StatusCode = 404;
                return null;
            }
            Quyen quyen = db.Quyens.SingleOrDefault(n => n.MaQuyen == id);
            if(quyen == null)
            {
                return HttpNotFound();
            }

            return View(quyen);
        }
        [HttpPost]
        public ActionResult ChinhSua([Bind(Include = "MaQuyen,TenQuyyen")] Quyen quyen)
        {
            //if (ModelState.IsValid)
            Quyen q =  db.Quyens.Find(quyen.MaQuyen);
            TryUpdateModel(q, new string[] { "MaQuyen", "TenQuyen"});       //ko dc phep doi ma quyen
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Xoa(string id)
        {
            if (id == "")
            {
                Response.StatusCode = 404;
                return null;
            }
            Quyen quyen = db.Quyens.SingleOrDefault(n => n.MaQuyen == id);

            if(quyen == null)
            {
                return HttpNotFound();
            }

            return View(quyen);
        }

        [HttpPost, ActionName("Xoa")]   //trùng tên
        public ActionResult XacNhanXoa(string id)
        {
            //lấy sp cần chỉnh sửa
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Quyen quyen = db.Quyens.SingleOrDefault(n => n.MaQuyen == id);
            if (quyen == null)
            {
                return HttpNotFound();
            }
            db.Quyens.Remove(quyen);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WebsiteBanHang/Views/QuanLyQuyen/ChinhSua.cshtml
@model WebsiteBanHang.Models.Quyen
@{
    ViewBag.Title = "Quản lý quyền";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Quản lý quyền", "Index") > Chỉnh sửa</h4>
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("ChinhSua", "QuanLyQuyen", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.Hidden("MaQuyen", Model.MaQuyen)
            <div class="form-group row ">
                <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaQuyen)</label>
                <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaQuyen)</div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.TenQuyen, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TenQuyen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenQuyen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row ">
                <div class="col-sm-4 mt-3">
                    <input type="submit" value="Chỉnh sửa" class="btn btn-sm btn-primary font-weight-bold w-25" />
                    @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                </div>
            </div>
        </div>
        }
    </div>
</div>

WebsiteBanHang/Views/QuanLyQuyen/Index.cshtml
@using WebsiteBanHang.Models
@model IEnumerable<Quyen>
@{
    ViewBag.Title = "Quản lý quyền";
    Layout = "~/Views/Layout/AdminLayout.cshtml";

    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<h2>@ViewBag.Title</h2>
<div class="card">
    <div class="card-body">
        <p>
            @Html.ActionLink("Thêm mới", "TaoMoi", null, htmlAttributes: new { @class = "btn btn-sm btn-warning font-weight-bold " })
        </p>
        @if (grid != null)
        {
            <div id="list" class="table-responsive">
                @grid.GetHtml(
                tableStyle: "table table-bordered table-hover",
                headerStyle: "",
                footerStyle: "text-center",
                numericLinksCount: 10,
                mode: WebGridPagerModes.All, firstText: "Trang đầu", lastText: "Trang cuối",
                columns: grid.Columns(
                    grid.Column("MaQuyen", "Mã quyền"),
                    grid.Column("TenQuyen", "Tên quyền"),
                    grid.Column(format: p => Html.ActionLink("Chỉnh sửa", "ChinhSua", new { id = p.MaQuyen })),
                    grid.Column(format: p => Html.ActionLink("Xóa", "Xoa", new { id = p.MaQuyen }))
                    )
                )
            </div>
        }
    </div>
</div>

WebsiteBanHang/Views/QuanLyQuyen/TaoMoi.cshtml
@model WebsiteBanHang.Models.Quyen
@{
    ViewBag.Title = "Quản lý quyền";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Quản lý quyền", "Index") > Tạo mới</h4>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Tạo mới quyền</h4>
        @using (Html.BeginForm("TaoMoi", "QuanLyQuyen", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    @Html.LabelFor(model => model.MaQuyen, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.MaQuyen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaQuyen, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.TenQuyen, htmlAttributes: new { @class = "col-form-label font-weight-bold col-sm-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.TenQuyen, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenQuyen, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row ">
                    <div class="col-sm-4 mt-3">
                        <input type="submit" value="Thêm mới" class="btn btn-sm btn-primary font-weight-bold w-25" />
                        @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

WebsiteBanHang/Views/QuanLyQuyen/Xoa.cshtml
@model WebsiteBanHang.Models.Quyen
@{
    ViewBag.Title = "Quản lý quyền";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h4>@Html.ActionLink("Quản lý quyền", "Index") > Xóa</h4>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin sản phẩm</h4>
        <hr />

        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.MaQuyen)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.MaQuyen)</div>
        </div>

        <div class="row ">
            <label class="col-sm-2 col-form-label font-weight-bold">@Html.DisplayNameFor(model => model.TenQuyen)</label>
            <div class="col-sm-6 col-form-label">@Html.DisplayFor(model => model.TenQuyen)</div>
        </div>

        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-4">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Xóa" class="btn btn-sm btn-primary font-weight-bold w-25" />
                    @Html.ActionLink("Trở về", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-secondary font-weight-bold w-25" })
                }
            </div>
        </div>
    </div>
</div>